### ISSUE TITLE
`role` attribute should be applied to child element, not wrapper.

### ISSUE THREAD

**Issue by greypants** [vigetlabs/react-focus-trap#14]
![image](https://cloud.githubusercontent.com/assets/647549/16779354/e2675f6e-483f-11e6-8090-d3ba4f4488fb.png)

Otherwise, screen readers will read this as "Navigation. One item", since there's only one immediate readable child.

**Comment by nhunzaker** [comment]
Good call. This should probably be a minor release.

**Comment by nhunzaker** [comment]
You good to handle this? Otherwise I've got bandwidth

**Comment by greypants** [comment]
can probably get to it later in the week, but if you've got bandwidth, go for it.

**Comment by nhunzaker** [comment]
@greypants After this change, think this ticket is sufficiently tested? https://github.com/vigetlabs/react-focus-trap/issues/9
