### ISSUE TITLE
Deprecate `React.createClass`

### ISSUE THREAD

**Issue by masylum** [vigetlabs/react-focus-trap#17]
React 16 is going to deprecate it.

![](https://www.dropbox.com/s/z6pn9zn38ze25fm/Screenshot%202017-05-04%2011.25.55.png?dl=1)

**Comment by nhunzaker** [comment]
Hmm. Yep. I'll stick it in the queue.

**Comment by nhunzaker** [comment]
Fixed with `react-focus-trap@2.4.0`. Would you be willing to take a look?

**Comment by masylum** [comment]
I don't use it directly but through a dependency, so I guess I will have to wait that they update the version 😄

**Comment by masylum** [comment]
Thanks a lot!
