### ISSUE TITLE
Unknown prop `onExit` on <div> tag

### ISSUE THREAD

**Issue by thejamespower** [vigetlabs/react-focus-trap#18]
Not sure if I'm just doing something really wrong here but this is my code: 
```js
return <FocusTrap active={this.props.menuVisible} onExit={this.escape}> 
...
```
Which fires a React error: 
Warning: Unknown prop `onExit` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by nhunzaker** [comment]
Hmm. Sorry for the delay. Looking into this.

**Comment by nhunzaker** [comment]
This was fixed in a prior release. Please give `react-focus-trap@2.5.0` a try (if it's still an issue).

**Comment by thejamespower** [comment]
Thanks @nhunzaker
