### ISSUE TITLE
Listener memory leak

### ISSUE THREAD

**Issue by hally9k** [vigetlabs/react-focus-trap#22]
I've just spent a while hunting down a little memory leak that we traced to this library. The event handlers on inputs that are left focussed when we unmounted a route in our app were being held and causing a leak. Have you come across this before? Is there anyway to ensure these are released from within focus-trap-react?

**Comment by nhunzaker** [comment]
Yikes! Thanks for bringing this to our attention.

My first guess is that the stack of focused elements has a stale reference:
https://github.com/vigetlabs/react-focus-trap/blob/master/src/focal-point.js#L8-L21

I'll do some investigation.

**Comment by nhunzaker** [comment]
Amazing what looking at something with fresh eyes will do... 

I'm working on a change that eliminates this stack. I'll send up a beta on NPM within the hour.

**Comment by nhunzaker** [comment]
I have sent out a PR here:
https://github.com/vigetlabs/react-focus-trap/pull/23

Some of this is guess work. But doing some snapshots, I am unable to see memory leaks. 

Would you mind pulling down `react-focus-trap@2.6.0-beta.0` from NPM?

**Comment by hally9k** [comment]
Sorry for the late reply, it's morning here now. Sure will feed back to you shortly.
I actually went further down the rabbit hole last night and ended up leaving this issue on the react repo:

https://github.com/facebook/react/issues/12947

These may or may not be related but definitely relevant.

**Comment by whs-dot-hk** [comment]
Hi, I created a test

https://github.com/vigetlabs/react-focus-trap/issues/22

**Comment by whs-dot-hk** [comment]
Hi, I create a test

https://whs-dot-hk.github.io/react-focus-trap-issue-22-test/

**Comment by nhunzaker** [comment]
Cool. I shipped 2.6.0, but I'm happy to follow up!
