### ISSUE TITLE
Focus trap should not be forced to 'unpause' when another trap is disabled

### ISSUE THREAD

**Issue by ChavdarSlavov** [vigetlabs/react-focus-trap#27]
Found an issue where one trap is incorrectly forced to unpause when another trap is disabled/destroyed.

Here is simple example:
 - Preview https://wkj3kk5307.codesandbox.io/
 - Code https://codesandbox.io/s/wkj3kk5307

Steps to reproduce: 
1. Click on 'btn 2' to remove second trap. 

Result: 
Trap 1 (with child 'btn 1') becomes active preventing 'btn 3' from being focused or clicked. 

Expectation: 
- Trap 1 (with child 'btn 1') should remain paused due `<FocusTrap paused={true}>`. 
- 'btn 3' should be focusable and clickable.

**Comment by nhunzaker** [comment]
Sorry to just get back to this - is this still an issue?
